### ISSUE TITLE
It would be nice to have the jenkins-status column width customizable

### ISSUE THREAD

**Issue by whirm** [rmuslimov/jenkins.el#14]
I have some jobs that all start with the same name with a few different letters at the end and they are getting eaten by the ellipsis so it makes it a bit awkward to search for them.

Thanks for jenkins.el btw, I'm using it daily and looks really promising! :)

**Comment by rmuslimov** [comment]
Yep, agree, I will add customization of column's width in near future. thanks!

**Comment by rmuslimov** [comment]
Done, please check how it works, you can simply set column size by calling code below in your init.el:

```
(setq jenkins-colwidth-name 35)
```

**Comment by whirm** [comment]
Works great, thanks!

**Comment by whirm** [comment]
I've noticed it won't apply when refreshing the buffer, I have to kill the buffer and recreate it.
I don't care particularly but it might be confusing to other people.

Thanks again!

**Comment by rmuslimov** [comment]
I'm not sure I'm going to implement reinitialization of table once variables changes
