### ISSUE TITLE
JSON read table error

### ISSUE THREAD

**Issue by featheredtoast** [rmuslimov/jenkins.el#16]
Hey there!

Just wanted to let you know that I'm running into a JSON read table error when setting this up with my Jenkins deployment, installed from MELPA.

On Jenkins v1.645.

I've got about ~50 jobs to list and ~20 nodes.

Willing to throw you debug stuff, but not sure what's useful here. Assuming it just doesn't want to parse out a ton of info?

**Comment by featheredtoast** [comment]
I'm gonna close this out, this seems to be unrelated to jenkins.el, sorry about that! ;)

**Comment by zachdaniel** [comment]
@featheredtoast Do you know what went wrong? I'm seeing the same symptoms.

**Comment by featheredtoast** [comment]
I don't, sorry - I was noticing the same error on both jenkins and jira plugins, leading me to think that this was something to do with my emacs installs, rather than an issue with the associated projects.
