### ISSUE TITLE
Job details erroring out

### ISSUE THREAD

**Issue by manojm321** [rmuslimov/jenkins.el#23]
Job overview works fine and it list all the jobs, but when I press RET on  a job I get the following error:

`Debugger entered--Lisp error: (wrong-type-argument listp 104)`

Tried to look through jenkins.el 

Following is the URL which gets generated:

http://jenkins/job/XXX/api/json?depth=1&tree=builds[number,timestamp,result,url,building,culprits[fullName]]

O/p on my browser:
`{"_class":"hudson.model.FreeStyleProject","builds":[{"_class":"hudson.model.FreeStyleBuild","building":false,"number":528,"result":"FAILURE","timestamp":1499910416613,"url":"http://jenkins/job/XXX/528/"},`
.......
}`

Let me know if you need more info.

**Comment by rmuslimov** [comment]
Thanks for reporting. Yep, seems like something major is broken, I will fix as soon as I will back from vacation.

**Comment by Wilfred** [comment]
I suspect this has been fixed by #21. @Manoj321 can you try the latest version?

**Comment by manojm321** [comment]
Awesome thanks for fixing, works as expected. One minor thing is the cursor goes to the end of the job details buffer. IMO it should be at the beginning or better yet at the latest job so that I can quickly view the console o/p. Anyway that's just me.
