### ISSUE TITLE
"End of file during parsing"

### ISSUE THREAD

**Issue by pmiddend** [rmuslimov/jenkins.el#6]
I'm getting "end of file during parsing" when executing M-x jenkins. I tried executing (jenkins-get-jobs-list), but got the same error and no output (after a few seconds of waiting).

I'd like to debug this by issuing the same request as jenkins.el using curl or a REST client, but I'm not sure on how to do it.

**Comment by rmuslimov** [comment]
Sorry for delay. Ok, let's try to get jenkins page using curl:

```
curl -X POST -H "application/x-www-form-urlencoded" -g -u <USER>:<PASSWORD> 'http://<URL_ADDRESS>/api/json?depth=2&tree=name,jobs[name,lastSuccessfulBuild[result,timestamp,duration,id],lastFailedBuild[result,timestamp,duration,id],lastBuild[result,executor[progress]],lastCompletedBuild[result]]'
```

Just replace three valiarbles in this command with proper your own values

**Comment by pmiddend** [comment]
Great, this works and returns a json object. It works even when I remove "-u <USER>:<PASSWORD>".

**Comment by rmuslimov** [comment]
Is the result is valid json object?

**Comment by pmiddend** [comment]
Yes it is. I experimented a bit and by removing the authentication header, I think the json is at least successfully retrieved. However, now I get "JSON readtable error". I suppose the json is in the wrong format.

**Comment by rmuslimov** [comment]
Ok, let's check if the format of json is ok, please try to execute this:

```
(json-read-from-string
 (jenkins--retrieve-page-as-json (jenkins-jobs-view-url)))
```

**Comment by rmuslimov** [comment]
I'm closing this, since there are no answer. I guess it was because of some issues with installation or etc. @pmiddend please open new issue if you get this again, and json you getting will be valid

**Comment by pmiddend** [comment]
Yeah, I'm sorry, I didn't have enough time to dig deep into this. I'll wait until a new jenkins version is installed at my company. Thanks anyway.
