### ISSUE TITLE
jenkins-hostname expects a trailing slash

### ISSUE THREAD

**Issue by brcm-ruperts** [rmuslimov/jenkins.el#9]
The variable `jenkins-hostname` gets used in `jenkins-jobs-view-url` in a way that assumes it has a slash at the end. This doesn't really match the usual meaning of "hostname", which would be something like `jenkins.my-company.com`.

**Comment by noorul** [comment]
Also this assumes that host name contains protocol. For me just hostname/ does not work, I need to give http://hostname:port/. Also I think we can separate out port. If not we can re-name the variable to something like jenkins-url

**Comment by rmuslimov** [comment]
You're right, I just replaces jenkins-hostname with jenkins-url variable. I think now it ok for this variable assume that it has slash in the end. 
@noorul You can just port in this jenkins-url variable ( as you could in jenkins-hostname before). I guess now it more clear and predictable behaviour ( to have everything protocol, domain and port at the same place)

**Comment by rmuslimov** [comment]
Since somebody already have installed this package I left things as backward compatible and will replace them as some point in future.
Thanks, for finding this issue. @brcm-ruperts @noorul
